[pytest]
addopts = --output=reports/playwright-report --tracing=retain-on-failure --video=retain-on-failure --screenshot=only-on-failure --html=reports/report.html --self-contained-html
api_base_url = https://jsonplaceholder.typicode.com
api_timeout = 10
