[pytest]
addopts = --alluredir=reports/allure-results --output=reports/playwright-artifacts --tracing=retain-on-failure --video=retain-on-failure --screenshot=only-on-failure
api_base_url = https://jsonplaceholder.typicode.com
api_timeout = 10
